### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by trallard** [SheffieldMLNet/sheffieldmlnet.github.io#1]
Choose and add a code of conduct for the network and activities

**Comment by trallard** [comment]
Apologies for leaving this too late. I think we'd be fine with the contributor covenant CoC: quite simple and to the point..... do not want to mess up with your code so will only add it here ⬇️

----

# Machine learning research network's Code of Conduct
Based on:
Contributor Covenant Code of Conduct

### Encouraged Behaviour
-	Using welcoming and inclusive language
-	Being respectful of differing viewpoints and experiences
-	Gracefully accepting constructive criticism
-	Focusing on what is best for the community
-	Showing empathy towards other community members

### Unacceptable Behaviour
-	The use of sexualized language or imagery and unwelcome sexual attention or advances
-	Trolling, insulting/derogatory comments, and personal or political attacks
-	Public or private harassment
-	Publishing others' private information, such as a physical or electronic address, without explicit permission
-	Other conduct which could reasonably be considered inappropriate in a professional setting

### How can I report a violation of the Code of Conduct?
-	Instances of abusive, harassing or otherwise unacceptable behaviour may be
reported by contacting the project team

**Comment by wilocw** [comment]
Reworded community/project to network and added link to contact info.

Created [repo to host CoC](../../code-of-conduct), will write short blog post and add to site.

Thanks @trallard .
